In [24]:
arr = [3,6,8,10,1,2]

In [2]:
len(arr)/2

3

In [3]:
arr[len(arr)/2]

10

In [4]:
print "hello"

hello


In [5]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

#1: cat
#2: dog
#3: monkey


In [20]:
nums = [1,2,3,4,5,6]
nums_cub = [x**3 for x in nums]
print nums, nums_cub

[1, 2, 3, 4, 5, 6] [1, 8, 27, 64, 125, 216]


In [8]:
nums = [1,2,3,4,5,6]
nums_cub = [x**3 for x in nums if x%2==0]
print nums, nums_cub

[1, 2, 3, 4, 5, 6] [8, 64, 216]


In [9]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

#1: fish
#2: dog
#3: cat


In [10]:
animals = {'cat', 'dog', 'fish', 'monkey', 'lion'}
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

#1: lion
#2: cat
#3: monkey
#4: fish
#5: dog


In [11]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print even_num_to_square  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


In [12]:
odd_nums_to_square = {x:x**3 for x in nums if x % 2 !=0}
print odd_nums_to_square

{1: 1, 3: 27}


In [13]:
nums[:]

[0, 1, 2, 3, 4]

In [15]:
import numpy as np
nums_arr = np.array(nums)

In [16]:
nums_arr

array([0, 1, 2, 3, 4])

In [25]:
nums_arr = np.array([np.array(nums), np.array(nums_cub), np.array(arr)])

In [26]:
nums_arr

array([[  1,   2,   3,   4,   5,   6],
       [  1,   8,  27,  64, 125, 216],
       [  3,   6,   8,  10,   1,   2]])

In [27]:
nums_arr.shape

(3, 6)

In [38]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [61]:
b = a[[1, 1, 2,1], [1, 1, 1,1]]
print b

[4 4 6 4]


In [40]:
a.shape

(3, 2)

In [41]:
b.shape

(3,)

In [50]:
print b

[1 1 1]


In [37]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
slicer = np.array([[0,1,1], [0,1,0]])

In [45]:
slicer

array([[0, 1, 1],
       [0, 1, 0]])

In [46]:
a[slicer]

array([[[1, 2],
        [3, 4],
        [3, 4]],

       [[1, 2],
        [3, 4],
        [1, 2]]])

In [105]:
x = np.array([[1,2],[3,4],[5,6],[7,8]], dtype=np.float64)
y = np.array([5], dtype=np.float64)

In [109]:
np.sqrt(np.sum((x-y)**2))

6.6332495807107996

In [64]:
x+y

array([[  6.,   8.],
       [ 10.,  12.]])

In [102]:
dist = np.linalg.norm(x-y)
print dist

6.63324958071


In [114]:
summer = 0.000000
distly = 0.000000
for i in xrange(x.shape[0]):
    for j in xrange(y.shape[0]):
        summer += np.sum(((x[i]-y[j])**2))
        print (x[i]-y[j])

summer
distly  = np.sqrt(float(summer))

[-4. -3.]
[-2. -1.]
[ 0.  1.]
[ 2.  3.]


In [115]:
distly

6.6332495807107996

In [82]:
y[0]

5.0

In [119]:
  def compute_distances_two_loops(Y, X):
    """
    Compute the distance between each test point in X and each training point
    in self.X_train using a nested loop over both the training data and the 
    test data.

    Inputs:
    - X: A numpy array of shape (num_test, D) containing test data.

    Returns:
    - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
      is the Euclidean distance between the ith test point and the jth training
      point.
    """
    num_test = X.shape[0]
    num_train = Y.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in xrange(num_test):
      for j in xrange(num_train):
        #####################################################################
        # TODO:                                                             #
        # Compute the l2 distance between the ith test point and the jth    #
        # training point, and store the result in dists[i, j]. You should   #
        # not use a loop over dimension.                                    #
        #####################################################################
        dists[i,j]=np.sqrt(((Y[i]-X[j])**2))
        #####################################################################
        #                       END OF YOUR CODE                            #
        #####################################################################
    return dists

In [121]:
M = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
N = np.array([[7,8],[8,9],[9,10]])
npdist = compute_distances_two_loops(M,N)

ValueError: setting an array element with a sequence.

In [145]:
num_test = N.shape[0]
num_train = M.shape[0]
dists = np.zeros((num_test, num_train))

num_test
num_train
dists

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [147]:
for i in xrange(num_test):
      for j in xrange(num_train):
        dists[i,j] = np.sqrt(np.sum(((M[j]-N[i])**2)))

In [149]:
dists

array([[  8.48528137,   7.07106781,   5.65685425,   4.24264069,
          2.82842712],
       [  9.89949494,   8.48528137,   7.07106781,   5.65685425,
          4.24264069],
       [ 11.3137085 ,   9.89949494,   8.48528137,   7.07106781,
          5.65685425]])

In [152]:
for i in xrange(num_test):
      dists[i, :] = np.sqrt(np.sum(((M-N[i])**2)))

In [153]:
dists

array([[ 13.41640786,  13.41640786,  13.41640786,  13.41640786,
         13.41640786],
       [ 16.43167673,  16.43167673,  16.43167673,  16.43167673,
         16.43167673],
       [ 19.49358869,  19.49358869,  19.49358869,  19.49358869,
         19.49358869]])

In [159]:
for i in xrange(num_test):
      for j in xrange(num_train):
        print i,j,((M[j]-N[i])**2)

0 0 [36 36]
0 1 [25 25]
0 2 [16 16]
0 3 [9 9]
0 4 [4 4]
1 0 [49 49]
1 1 [36 36]
1 2 [25 25]
1 3 [16 16]
1 4 [9 9]
2 0 [64 64]
2 1 [49 49]
2 2 [36 36]
2 3 [25 25]
2 4 [16 16]


In [166]:
for i in xrange(num_test):
    print i, np.sqrt(np.sum((M-N[i])**2, axis=1))
    dists[i,:] = np.sqrt(np.sum((M-N[i])**2, axis=1))

0 [ 8.48528137  7.07106781  5.65685425  4.24264069  2.82842712]
1 [ 9.89949494  8.48528137  7.07106781  5.65685425  4.24264069]
2 [ 11.3137085    9.89949494   8.48528137   7.07106781   5.65685425]


In [167]:
dists

array([[  8.48528137,   7.07106781,   5.65685425,   4.24264069,
          2.82842712],
       [  9.89949494,   8.48528137,   7.07106781,   5.65685425,
          4.24264069],
       [ 11.3137085 ,   9.89949494,   8.48528137,   7.07106781,
          5.65685425]])

In [176]:
N.reshape(6,1)-M.reshape(10,1)

ValueError: operands could not be broadcast together with shapes (6,1) (10,1) 

In [177]:
M

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [178]:
N

array([[ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [179]:
M+N

ValueError: operands could not be broadcast together with shapes (5,2) (3,2) 

In [182]:
M.reshape(1,10)

array([[1, 2, 2, 3, 3, 4, 4, 5, 5, 6]])

In [183]:
N.reshape(1,6)

array([[ 7,  8,  8,  9,  9, 10]])

In [185]:
M.reshape(1,10)-N.reshape(1,6)

ValueError: operands could not be broadcast together with shapes (1,10) (1,6) 

In [186]:
M

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [187]:
N.dot(M.T)

array([[ 23,  38,  53,  68,  83],
       [ 26,  43,  60,  77,  94],
       [ 29,  48,  67,  86, 105]])

In [188]:
M.dot(M.T)

array([[ 5,  8, 11, 14, 17],
       [ 8, 13, 18, 23, 28],
       [11, 18, 25, 32, 39],
       [14, 23, 32, 41, 50],
       [17, 28, 39, 50, 61]])

In [189]:
M.dot(M)

ValueError: shapes (5,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [190]:
M**2

array([[ 1,  4],
       [ 4,  9],
       [ 9, 16],
       [16, 25],
       [25, 36]])

In [191]:
M**2 + N **2 - 2*N.dot(M.T)

ValueError: operands could not be broadcast together with shapes (5,2) (3,2) 

In [192]:
N**2

array([[ 49,  64],
       [ 64,  81],
       [ 81, 100]])

In [193]:
N.dot(M.T)

array([[ 23,  38,  53,  68,  83],
       [ 26,  43,  60,  77,  94],
       [ 29,  48,  67,  86, 105]])

In [194]:
M

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [195]:
N

array([[ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [197]:
M_sq = M*M
M_sq = np.sum(M_sq, axis=1)
M_sq

array([ 5, 13, 25, 41, 61])

In [198]:
M_sq_rep = np.array([M_sq]*N.shape[0])

In [199]:
M_sq_rep

array([[ 5, 13, 25, 41, 61],
       [ 5, 13, 25, 41, 61],
       [ 5, 13, 25, 41, 61]])

In [202]:
N_sq = N*N
N_sq = np.sum(N_sq, axis=1)
print N_sq
N_sq_rep = np.array([N_sq]*M.shape[0]).T
print N_sq_rep

[113 145 181]
[[113 113 113 113 113]
 [145 145 145 145 145]
 [181 181 181 181 181]]


In [203]:
N.dot(M.T)

array([[ 23,  38,  53,  68,  83],
       [ 26,  43,  60,  77,  94],
       [ 29,  48,  67,  86, 105]])

In [2]:
import numpy as np
x = np.array([[5, 4], [3, 6]])

In [3]:
#Expected Output
#[[1,0],[0,1]]
np.argsort(x, axis=0)

array([[1, 0],
       [0, 1]])

In [4]:
#Expected output
#[[1,0],[0,1]]
np.argsort(x, axis=1)

array([[1, 0],
       [0, 1]])

In [9]:
y = np.array([[5, 9, 4], [3, 6, 8], [1,2,7]])

In [10]:
#Expected Output
#[[2,1,0],[1,2,0],[1,2,0]]
np.argsort(y, axis=0)

array([[2, 2, 0],
       [1, 1, 2],
       [0, 0, 1]])

In [7]:
np.argsort(y, axis=1)

array([[1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
y

array([[5, 4, 4],
       [3, 6, 8],
       [1, 1, 1]])

In [23]:
arr = np.array([4,4,4,1,1,1,2,3,3])
pivot = arr[len(arr) / 2]

In [12]:
pivot

4

In [14]:
len(arr)/2

1

In [25]:
idx = np.argsort(arr)

In [27]:
idx

array([3, 4, 5, 6, 7, 8, 0, 1, 2])

In [26]:
arr[idx]

array([1, 1, 1, 2, 3, 3, 4, 4, 4])

In [19]:
ties = np.array([[5, 4, 4],
       [3, 6, 8],
       [1, 1, 1]])

In [28]:
rows = np.argsort(ties, axis=1)
rows

array([[1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [31]:
cols = np.argsort(ties, axis=0)
cols

array([[2, 2, 2],
       [1, 0, 0],
       [0, 1, 1]])

In [35]:
ties_idx = ties[:, rows]
ties_idx

array([[[4, 4, 5],
        [5, 4, 4],
        [5, 4, 4]],

       [[6, 8, 3],
        [3, 6, 8],
        [3, 6, 8]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [34]:
ties.shape

(3, 3)

In [36]:
ties_idx.shape

(3, 3, 3)

In [38]:
ties[rows[:,2]]

array([[5, 4, 4],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
dists = np.random.random((500,500))


In [41]:
dists

array([[ 0.64171182,  0.13414621,  0.50851291, ...,  0.02174592,
         0.93166835,  0.88625982],
       [ 0.14197099,  0.91760463,  0.68201066, ...,  0.58930719,
         0.97988541,  0.46958875],
       [ 0.08868529,  0.88804921,  0.17500606, ...,  0.3014671 ,
         0.21168146,  0.40727779],
       ..., 
       [ 0.72479115,  0.97245899,  0.49976224, ...,  0.01558811,
         0.02718399,  0.02623468],
       [ 0.03731851,  0.76432808,  0.99296351, ...,  0.57354949,
         0.34820305,  0.00154338],
       [ 0.88323125,  0.4914054 ,  0.48888424, ...,  0.29177265,
         0.35580226,  0.08498625]])

In [43]:
y_train = np.arange(10)(*shape)

ValueError: operands could not be broadcast together with shapes (500,) (10,) 

In [45]:
y_train = np.random.random_integers(0, 9, size=(500))

/apps/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  if __name__ == '__main__':


In [46]:
y_train

array([3, 0, 3, 6, 0, 1, 0, 1, 3, 0, 2, 5, 1, 1, 6, 4, 2, 7, 7, 8, 4, 2, 4,
       0, 4, 9, 4, 7, 7, 6, 5, 6, 0, 2, 1, 3, 0, 8, 7, 5, 5, 8, 8, 0, 3, 3,
       2, 9, 9, 3, 0, 5, 7, 2, 0, 2, 1, 9, 5, 9, 6, 4, 2, 1, 3, 6, 6, 8, 2,
       4, 0, 5, 6, 8, 7, 8, 6, 9, 4, 4, 5, 5, 9, 2, 2, 4, 3, 0, 8, 5, 1, 1,
       4, 6, 4, 7, 2, 9, 6, 4, 5, 0, 1, 7, 3, 8, 3, 9, 8, 4, 5, 6, 1, 5, 0,
       4, 4, 2, 8, 3, 9, 9, 5, 5, 6, 8, 5, 6, 6, 6, 9, 1, 3, 7, 2, 2, 7, 9,
       7, 6, 8, 8, 7, 3, 8, 0, 1, 9, 4, 4, 7, 5, 5, 9, 9, 4, 3, 5, 1, 5, 6,
       5, 3, 5, 5, 9, 3, 3, 1, 7, 7, 7, 2, 6, 5, 5, 9, 8, 6, 7, 4, 7, 9, 7,
       9, 3, 0, 6, 6, 0, 8, 2, 6, 0, 3, 9, 1, 5, 4, 2, 7, 2, 1, 3, 0, 0, 8,
       3, 1, 6, 5, 4, 6, 8, 2, 4, 6, 8, 8, 4, 3, 7, 2, 4, 2, 4, 4, 4, 3, 2,
       8, 6, 0, 4, 5, 0, 6, 6, 0, 5, 4, 4, 0, 8, 6, 1, 7, 2, 2, 5, 9, 9, 8,
       3, 9, 9, 6, 4, 4, 2, 3, 8, 0, 0, 9, 6, 7, 1, 9, 5, 7, 7, 3, 2, 3, 1,
       4, 1, 8, 7, 4, 5, 0, 5, 2, 9, 5, 8, 4, 7, 2, 7, 7, 0, 3, 8, 6, 1, 5,
       7, 6,

In [73]:
from collections import Counter
k = 1
num_test = dists.shape[0]
y_pred = np.zeros(num_test, dtype = int)

for i in xrange(num_test):
      # A list of length k storing the labels of the k nearest neighbors to
      # the ith test point.
    closest_y = []
    sorted_idx = np.argsort(dists[i,:])
    y_sorted = y_train[sorted_idx]
    closest_y = y_sorted[:(k+1)]
    dict_y = Counter(closest_y)
    [v for v in sorted(dict_y.iteritems(), key=lambda(k, v): (v, -k))]
    min_index = v[0]
    y_pred[i] = min_index
    
       #########################################################################
      # TODO:                                                                 #
      # Use the distance matrix to find the k nearest neighbors of the ith    #
      # testing point, and use self.y_train to find the labels of these       #
      # neighbors. Store these labels in closest_y.                           #
      # Hint: Look up the function numpy.argsort.                             #
      #########################################################################
      #min_index = np.argmin(dists)
        
    
      #########################################################################
      # TODO:                                                                 #
      # Now that you have found the labels of the k nearest neighbors, you    #
      # need to find the most common label in the list closest_y of labels.   #
      # Store this label in y_pred[i]. Break ties by choosing the smaller     #
      # label.                                                                #
      #########################################################################
     # predict the label of the nearest example
    
print y_sorted
print closest_y
print dict_y
print v
print min_index
print v[0]
print y_pred

[8 0 0 6 6 2 1 0 4 4 4 5 2 3 8 2 3 8 5 8 8 4 3 5 4 3 1 3 3 0 1 5 8 4 0 2 4
 9 7 9 6 8 8 4 5 9 1 2 9 4 5 4 0 6 7 3 4 3 4 5 2 8 5 9 6 3 7 7 6 5 5 0 4 4
 2 3 5 6 4 5 5 3 2 5 7 9 1 4 7 9 4 0 1 4 1 5 3 0 6 7 3 1 5 6 7 9 8 6 0 4 6
 7 4 5 0 1 0 4 4 9 9 7 9 8 3 7 9 4 1 9 7 4 8 6 4 5 1 8 9 4 2 4 5 0 3 8 3 8
 5 8 5 8 7 8 5 2 8 5 7 2 8 2 5 4 8 6 8 8 5 8 4 6 2 6 9 7 6 1 7 4 9 9 2 7 6
 4 0 2 1 5 9 5 9 8 7 2 6 0 0 5 9 5 7 0 5 9 3 7 0 2 6 3 9 6 5 2 1 8 8 9 1 3
 2 1 4 5 7 9 5 0 6 6 4 7 5 2 0 0 6 7 8 2 2 6 4 4 4 2 6 3 5 5 3 3 6 4 2 6 3
 3 6 0 7 4 1 1 2 5 3 4 4 5 7 6 2 6 7 1 8 1 7 7 7 7 9 0 3 8 6 5 6 6 3 0 2 0
 8 9 5 3 0 9 4 6 5 5 0 4 1 7 2 2 7 0 6 1 1 6 6 0 0 9 0 9 1 6 0 6 1 9 0 3 5
 5 2 4 2 2 3 8 9 0 1 4 3 1 6 9 1 1 3 4 7 9 1 6 7 3 8 4 3 9 5 5 8 1 8 5 7 4
 5 3 7 4 8 6 8 6 9 2 6 6 0 0 9 9 5 8 0 7 8 4 6 7 7 8 2 3 9 2 6 1 1 3 6 9 6
 2 2 7 2 1 5 8 2 3 9 8 3 2 4 4 6 2 6 7 9 7 9 1 4 9 6 6 6 4 3 1 0 7 4 8 9 0
 8 3 7 8 2 0 1 8 4 4 2 2 4 8 7 8 4 0 9 7 4 7 4 5 2 3 7 2 0 9 1 9 0 3 7 7 2
 1 9 7 1 1 9 2 9 4 6 0 8 